const {chromium}=require(process.env.COURSE_PLAYWRIGHT || 'playwright');
const fs=require('fs');const path=require('path');const {pathToFileURL,fileURLToPath}=require('url');
(async()=>{
const dir=path.resolve(process.argv[2]||'信号与系统/Lectures/L02');const out=dir+'/assets/qa';fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.setOffline(true);
const page=await context.newPage();const errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))requests.push(r.url())});
await page.goto(pathToFileURL(dir+'/Review.html').href);await page.waitForFunction(()=>document.querySelectorAll('.katex').length>100);await page.evaluate(()=>document.fonts.ready);await page.addStyleTag({content:'html{scroll-behavior:auto!important}'});
const links=await page.locator('[href],[src]').evaluateAll(es=>es.map(e=>({tag:e.tagName,url:e.getAttribute('href')||e.getAttribute('src')})));
const broken=[];for(const l of links){if(!l.url||l.url.startsWith('data:'))continue;const u=new URL(l.url,pathToFileURL(dir+'/Review.html'));if(u.protocol!=='file:')continue;if(!fs.existsSync(fileURLToPath(u)))broken.push(l);else if(u.hash&&fileURLToPath(u)===path.resolve(dir+'/Review.html')){if(!await page.locator('[id]').evaluateAll((es,id)=>es.some(e=>e.id===id),decodeURIComponent(u.hash.slice(1))))broken.push(l)}}
const duplicateIds=await page.locator('[id]').evaluateAll(es=>{let a=es.map(e=>e.id);return a.filter((x,i)=>a.indexOf(x)!==i)});
const modes={};for(const mode of ['notes','transcript','sources']){await page.locator(`[data-mode="${mode}"]`).click();await page.evaluate(async()=>{document.querySelectorAll('article:not([hidden]) details').forEach(d=>d.open=true);await Promise.all([...document.querySelectorAll('article:not([hidden]) img')].map(img=>{img.loading='eager';return img.decode().catch(()=>{})}))});const h=await page.evaluate(()=>document.documentElement.scrollHeight);for(let y=0;y<h;y+=800){await page.evaluate(y=>window.scrollTo(0,y),y);await page.waitForTimeout(15)}
await page.waitForTimeout(250);modes[mode]=await page.locator('#'+mode).evaluate(e=>({headings:e.querySelectorAll('h2').length,math:e.querySelectorAll('.katex').length,mathErrors:[...e.querySelectorAll('.katex-error')].map(x=>x.textContent),brokenImages:[...e.querySelectorAll('img')].filter(x=>!x.complete||!x.naturalWidth).map(x=>x.src),overflow:document.documentElement.scrollWidth>innerWidth}));await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:out+'/'+mode+'-top.png'});}
await page.evaluate(()=>location.hash='N05');await page.waitForTimeout(700);await page.screenshot({path:out+'/derivation.png'});
await page.evaluate(()=>location.hash='T12');await page.waitForTimeout(700);if(!await page.locator('#transcript').isVisible())errors.push('hash view switch failed');await page.screenshot({path:out+'/transcript-middle.png'});
await page.locator('#transcript img').first().click();if(!await page.locator('#lightbox').isVisible())errors.push('lightbox failed');await page.locator('#close-image').click();
await page.locator('[data-seek="2023"]').click();await page.waitForTimeout(300);const audio=await page.locator('audio').evaluate(a=>({currentTime:a.currentTime,duration:a.duration,error:a.error?.message}));
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>location.hash='N12');await page.waitForTimeout(700);await page.screenshot({path:out+'/mobile-formula.png'});const mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
const report={offline:true,externalRequests:requests,errors,brokenLinks:broken,duplicateIds,modes,audio,mobileOverflow};fs.writeFileSync(out+'/browser-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
